### ISSUE TITLE
a question about early start

### ISSUE THREAD

**Issue by t00197857** [cmusatyalab/elijah-provisioning#5]
Hello。 I have a question about early start。As the paper “Just-in-Time Provisioning for Cyber Foraging” said，“We make a reasonable attempt to order the chunks according to a profiled access pattern
computed offline”，and I studied the code under this project，I haven’t found the corresponding code about  how to make chucks in order。maybe I'm not careful enough，can you help me?

**Comment by krha** [comment]
Hi,

This repo does not include the  profiling code for chunk access order.

https://github.com/cmusatyalab/elijah-provisioning/blob/master/cloudletfs/cloudletfs/fuse.c#L170

This part (in FUSE file system) tells you disk & memory access order when the VM is launched. Base on this information, you can create your own profiler. Thank you.
